---
title: "Louis' Practice Document"
author: "Louis"
output: github_document
---

## Setup

```{r install_ggradar, message = FALSE}
devtools::install_github("ricardo-bion/ggradar", 
                          dependencies = TRUE)
```

```{r Setup, message = FALSE}
library(tidyverse)
library(here)
library(ggridges)
library(ggradar)
library(hexbin)
spotify_songs <- readr::read_csv(here('data/Spotify.csv'))
```

```{r define-data, message=FALSE}
edm_songs <- spotify_songs %>%
  filter(playlist_genre == "edm")
feature_names <- names(spotify_songs)[12:23]
```

```{r clean-dataframe}
clean_songs <- spotify_songs %>%
  filter(duplicated(track_name) == FALSE)
clean_edm <- spotify_songs %>%
  filter(playlist_genre == "edm") %>%
  filter(duplicated(track_name) == FALSE)
clean_rock <- spotify_songs %>%
  filter(playlist_genre == "rock") %>%
  filter(duplicated(track_name) == FALSE)
clean_pop <- spotify_songs %>%
  filter(playlist_genre == "pop") %>%
  filter(duplicated(track_name) == FALSE)
clean_rap <- spotify_songs %>%
  filter(playlist_genre == "rap") %>%
  filter(duplicated(track_name) == FALSE)
clean_rnb <- spotify_songs %>%
  filter(playlist_genre == "r&b") %>%
  filter(duplicated(track_name) == FALSE)
clean_latin <- spotify_songs %>%
  filter(playlist_genre == "latin") %>%
  filter(duplicated(track_name) == FALSE)
clean_full <- rbind(clean_edm, clean_latin, clean_pop, clean_rap,  clean_rnb, clean_rock)
```

## Including Code

```{r EDM-test}
edm_songs%>%
  select(c('playlist_genre', all_of(feature_names),track_popularity)) %>%
  #filter(track_popularity > 75) %>%
  pivot_longer(cols = feature_names) %>%
  group_by(name)%>%
  ggplot(aes(x = value, colour = name)) +
  geom_density(alpha = 0.5) +
  facet_wrap(~name, scales = "free") +
  labs(title = 'Spotify Audio Feature Density - by Genre',
       x = 'Value', y = 'Density')
```

```{r EDM-top10}
edm_songs%>%
  select(feature_names,track_popularity,track_name) %>%
  slice_max(track_popularity, n = 10) %>%
  pivot_longer(cols = feature_names) %>%
  group_by(name)%>%
  ggplot(aes(x = value, colour = name)) +
  geom_density(alpha = 0.5) +
  facet_wrap(~name, scales = "free")

edm_songs%>%
  select(feature_names,track_popularity,track_name) %>%
  slice_min(track_popularity, n = 10) %>%
  pivot_longer(cols = feature_names) %>%
  group_by(name)%>%
  ggplot(aes(x = value, colour = name)) +
  geom_density(alpha = 0.5) +
  facet_wrap(~name, scales = "free")
```

```{r timeline}
spotify_songs %>%
  mutate(track_album_release_date = as.integer(str_sub(track_album_release_date, end = 4))) %>%
  ggplot(aes(x = track_album_release_date, fill = playlist_genre)) +
  geom_histogram(binwidth = 2)
spotify_songs %>%
  mutate(track_album_release_date = as.integer(str_sub(track_album_release_date, end = 4))) %>%
  group_by(playlist_genre, track_album_release_date) %>%
  summarise(mean_track_popularity =mean(track_popularity)) %>%
  ggplot(aes(x = track_album_release_date, y = mean_track_popularity, colour = playlist_genre)) +
  geom_line() +
  theme_minimal() +
  facet_wrap(~playlist_genre)
```

#quick analysis

The top 10 seem to have much smoother graphs, meaning more variation

## Plan a strategy

I want to create a way of expressing songs based on their characteristics, I believe it's called a radar chart

```{r radar, echo=FALSE}
edm_songs %>%
  slice_max(track_popularity, n = 5) %>%
  group_by(track_name) %>%
  mutate(track_name = str_c(track_name,' ',toString(track_popularity))) %>%
  select(track_name, danceability, energy, key, speechiness, acousticness, instrumentalness,
         liveness, valence) %>%
  mutate(key = key/12) %>%
  ggradar(grid.max = 1)
```